@baseUrl = http://localhost:4101
@ruleId = 694d871855166f5016a9fb41
@agentId = agent-100

### agent-service health
GET http://localhost:4100/agents/health


###
# Report #1
# → زمان رخدادهای rule برای یک agent در یک بازه زمانی
GET {{baseUrl}}/reports/rule/{{ruleId}}/agent/{{agentId}}?last=1h&page=1&limit=10


###
# Report #2
# لیست agentها مرتب بر اساس تعداد رخداد rule
GET {{baseUrl}}/reports/rule/{{ruleId}}/agents?top=10


### create rule
# "name": "High temperature",
# "eventName": "temperature", // pressure, speed, voltage, noise, light
# "operator": ">", // '>', '<', '=', '>=', '<='
# "threshold": 80 // 0 to 120
POST {{baseUrl}}/rules
Content-Type: application/json

{
  "name": "High temperature",
  "eventName": "temperature",
  "operator": ">",
  "threshold": 22
}


### update rule
PUT {{baseUrl}}/rules/694d84b23865d7c695cd6986
Content-Type: application/json

{
  "threshold": 33
}

### delete
DELETE {{baseUrl}}/rules/694d84b23865d7c695cd6986
